curl -X 'GET' 
  'http://localhost:3000/person/create?id=1&name=Irina&age=18' 
  
###

curl -X 'GET' 
  'http://localhost:3000/person/2' 

###

POST http://localhost:3000/person/create HTTP/1.1
content-type: application/json

{
  "id": 2, 
  "name":"Fedr", 
  "age": 15
}
